<?php
namespace KhorshidLMS\Core;
if ( ! defined( 'ABSPATH' ) ) exit;
final class Admin {
 public static function hooks(): void { add_action('admin_menu',[self::class,'menu']); add_action('admin_post_kh_lms_save_course',[self::class,'save']); add_action('admin_enqueue_scripts',[self::class,'assets']); }
 public static function menu(): void { add_menu_page('مدیریت دوره‌ها','مدیریت دوره‌ها','manage_options','kh-lms', [self::class,'dashboard'],'dashicons-welcome-learn-more',26); add_submenu_page('kh-lms','افزودن دوره','افزودن دوره','manage_options','kh-lms-edit',[self::class,'edit']); }
 public static function assets(string $hook): void { if(strpos($hook,'kh-lms')===false)return; wp_enqueue_style('kh-lms-admin',KH_LMS_URL.'assets/css/admin.css',[],KH_LMS_VERSION); wp_enqueue_script('kh-lms-admin',KH_LMS_URL.'assets/js/admin.js',[],KH_LMS_VERSION,true); }
 public static function dashboard(): void { if(!current_user_can('manage_options'))wp_die('دسترسی غیرمجاز'); $courses=Repository::courses(['status'=>'publish']); echo '<div class="wrap kh-lms-admin"><h1>مدیریت دوره‌ها</h1><a class="button button-primary" href="'.esc_url(admin_url('admin.php?page=kh-lms-edit')).'">افزودن دوره جدید</a><div class="kh-grid">'; foreach($courses as $c) echo '<div class="kh-card"><h2>'.esc_html($c->title).'</h2><p>'.esc_html($c->course_code).'</p><a href="'.esc_url(admin_url('admin.php?page=kh-lms-edit&id='.$c->id)).'">ویرایش دوره و سرفصل‌ها</a></div>'; echo '</div></div>'; }
 public static function edit(): void { if(!current_user_can('manage_options'))wp_die('دسترسی غیرمجاز'); $c=isset($_GET['id'])?Repository::course(absint($_GET['id'])):null; $curr=$c?Repository::curriculum($c->id):[]; $nonce=wp_create_nonce('kh_lms_save_course'); echo '<div class="wrap kh-lms-admin"><h1>'.($c?'ویرایش دوره':'افزودن دوره جدید').'</h1><form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="kh_lms_save_course"><input type="hidden" name="course_id" value="'.esc_attr($c->id??0).'"> <input type="hidden" name="_wpnonce" value="'.esc_attr($nonce).'">'; echo '<div class="kh-card"><label>عنوان دوره<input required name="title" value="'.esc_attr($c->title??'').'"></label><label>توضیح کوتاه<textarea name="short_description">'.esc_textarea($c->short_description??'').'</textarea></label><label>توضیحات کامل<textarea name="description" rows="6">'.esc_textarea($c->description??'').'</textarea></label><label>نوع دوره<select name="type"><option value="free">رایگان</option><option value="paid" '.selected($c->type??'', 'paid',false).'>پولی</option></select></label><label>وضعیت<select name="status"><option value="draft">پیش‌نویس</option><option value="publish" '.selected($c->status??'', 'publish',false).'>منتشر شده</option></select></label></div><div class="kh-card"><h2>برنامه آموزشی</h2><div id="kh-curriculum">'; foreach($curr as $i=>$ch){echo '<div class="kh-chapter"><input name="chapters['.$i.'][title]" placeholder="عنوان فصل" value="'.esc_attr($ch->title).'"> <button type="button" class="button kh-remove">حذف</button><div class="kh-lessons">'; foreach($ch->lessons as $j=>$l) echo '<div class="kh-lesson"><input name="chapters['.$i.'][lessons]['.$j.'][title]" placeholder="عنوان درس" value="'.esc_attr($l->title).'"> <select name="chapters['.$i.'][lessons]['.$j.'][content_type]"><option value="text">متن</option><option value="video" '.selected($l->content_type,'video',false).'>ویدئو</option></select><input name="chapters['.$i.'][lessons]['.$j.'][video_url]" placeholder="URL ویدئو (فقط سمت سرور)" value="'.esc_attr($l->video_url).'"> <input name="chapters['.$i.'][lessons]['.$j.'][is_preview]" type="checkbox" value="1" '.checked($l->is_preview,1,false).'> پیش‌نمایش</div>'; echo '</div><button type="button" class="button kh-add-lesson">افزودن درس</button></div>'; } echo '</div><button type="button" class="button" id="kh-add-chapter">افزودن فصل</button></div><p><button class="button button-primary">ذخیره دوره</button></p></form></div>'; }
 public static function save(): void { if(!current_user_can('manage_options')||!check_admin_referer('kh_lms_save_course'))wp_die('درخواست نامعتبر'); global $wpdb; $id=absint($_POST['course_id']??0); $title=sanitize_text_field(wp_unslash($_POST['title']??'')); if(!$title)wp_die('عنوان الزامی است'); $now=current_time('mysql',true); $data=['title'=>$title,'slug'=>sanitize_title($title),'short_description'=>sanitize_textarea_field(wp_unslash($_POST['short_description']??'')),'description'=>wp_kses_post(wp_unslash($_POST['description']??'')),'type'=>sanitize_key($_POST['type']??'free'),'status'=>sanitize_key($_POST['status']??'draft'),'updated_at'=>$now]; if($id)$wpdb->update(Repository::table('courses'),$data,['id'=>$id]); else{$data+=['course_code'=>'KH-LMS-'.str_pad((string)(time()%100000),5,'0',STR_PAD_LEFT),'author_id'=>get_current_user_id(),'created_at'=>$now];$wpdb->insert(Repository::table('courses'),$data);$id=(int)$wpdb->insert_id;} $wpdb->delete(Repository::table('chapters'),['course_id'=>$id]); $wpdb->delete(Repository::table('lessons'),['course_id'=>$id]); foreach((array)($_POST['chapters']??[]) as $ci=>$ch){$ct=sanitize_text_field(wp_unslash($ch['title']??''));if(!$ct)continue;$wpdb->insert(Repository::table('chapters'),['course_id'=>$id,'title'=>$ct,'description'=>'','sort_order'=>(int)$ci,'created_at'=>$now,'updated_at'=>$now]);$cid=(int)$wpdb->insert_id;foreach((array)($ch['lessons']??[]) as $li=>$l){$lt=sanitize_text_field(wp_unslash($l['title']??''));if(!$lt)continue;$wpdb->insert(Repository::table('lessons'),['course_id'=>$id,'chapter_id'=>$cid,'title'=>$lt,'slug'=>sanitize_title($lt.'-'.$id.'-'.$li),'description'=>'','content_type'=>sanitize_key($l['content_type']??'text'),'content'=>'','video_url'=>sanitize_url($l['video_url']??''),'sort_order'=>(int)$li,'is_preview'=>empty($l['is_preview'])?0:1,'created_at'=>$now,'updated_at'=>$now]);}} wp_safe_redirect(admin_url('admin.php?page=kh-lms-edit&id='.$id.'&updated=1'));exit; }
}
