<?php
namespace KhorshidLMS\Core;
if ( ! defined( 'ABSPATH' ) ) exit;
final class Frontend {
 public static function hooks(): void { add_shortcode('kh_lms_course',[self::class,'course']); add_shortcode('kh_lms_my_courses',[self::class,'my_courses']); add_action('wp_enqueue_scripts',[self::class,'assets']); add_action('woocommerce_account_my-courses_endpoint',[self::class,'my_courses']); add_filter('query_vars',static function($v){$v[]='my-courses';return $v;}); }
 public static function assets(): void { if(is_singular()||is_account_page()){wp_enqueue_style('kh-lms-frontend',KH_LMS_URL.'assets/css/frontend.css',[],KH_LMS_VERSION);wp_enqueue_script('kh-lms-frontend',KH_LMS_URL.'assets/js/frontend.js',[],KH_LMS_VERSION,true);wp_localize_script('kh-lms-frontend','khLms',['api'=>esc_url_raw(rest_url('kh-lms/v1/')),'nonce'=>wp_create_nonce('wp_rest')]);} }
 public static function course($atts): string { $id=absint($atts['id']??$atts['course']??0);$c=Repository::course($id);if(!$c)return '<p>دوره پیدا نشد.</p>';$en=get_current_user_id()&&Repository::enrolled(get_current_user_id(),$id);$html='<article class="kh-course"><header><h1>'.esc_html($c->title).'</h1><p>'.esc_html($c->short_description).'</p>'.(!$en&&$c->type==='paid'?'<a class="kh-button" href="'.esc_url(wc_get_cart_url()).'">خرید دوره</a>':'').'</header><div class="kh-curriculum">';foreach(Repository::curriculum($id) as $ch){$html.='<section><h2>'.esc_html($ch->title).'</h2><ul>';foreach($ch->lessons as $l){$allowed=$en||$l->is_preview||$c->type==='free';$html.='<li>'.($allowed?'▶':'🔒').' '.esc_html($l->title).'</li>';} $html.='</ul></section>';}return $html.'</div></article>'; }
 public static function my_courses(): void { if(!is_user_logged_in()){echo '<p>برای مشاهده دوره‌های خود وارد شوید.</p>';return;} global $wpdb;$rows=$wpdb->get_results($wpdb->prepare('SELECT c.* FROM '.Repository::table('courses').' c INNER JOIN '.Repository::table('enrollments').' e ON e.course_id=c.id WHERE e.user_id=%d AND e.status=%s',get_current_user_id(),'active'));echo '<div class="kh-courses"><h2>دوره‌های شما</h2>';foreach($rows as $c)echo '<div class="kh-card"><h3>'.esc_html($c->title).'</h3>'.do_shortcode('[kh_lms_course id="'.(int)$c->id.'"]').'</div>';echo '</div>'; }
}
